services:
  - type: web
    name: field-service-management-api
    runtime: docker
    region: singapore
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "8080"
