services:
  - type: web
    name: field-service-management-api
    runtime: go
    buildCommand: go build -tags netgo -ldflags '-s -w' -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: "8080"
